api/v1/manager/urls.py
from django.urls import path

from api.v1.manager import views


urlpatterns = [
    path('login/', views.login),

    path('category/', views.category),
    path('category/add/', views.category_add),
    path('category/edit/<int:pk>/', views.category_edit),
    path('category/delete/<int:pk>/', views.category_delete),

    path('item/', views.item),
    path('item/add/', views.item_add),
    path('item/edit/<int:pk>/', views.item_edit),
    path('item/delete/<int:pk>/', views.item_delete),

    path('franchise/', views.franchise),
    path('franchise/add/', views.franchise_add),
    path('franchise/edit/<int:pk>/', views.franchise_edit),
    path('franchise/delete/<int:pk>/', views.franchise_delete),

    path('franchise/user/', views.franchise_user),
    path('franchise/user/add/', views.franchise_user_add),
    # path('franchise/user/edit/<int:pk>/', views.franchise_user_edit),
    path('franchise/user/delete/<int:pk>/', views.franchise_user_delete),

    # path('item/assign/', views.item_assign),
    # path('item/assign/edit/<int:pk>/', views.item_assign_edit),
    # path('item/assign/delete/<int:pk>/', views.item_assign_delete),

]

franchise/urls.py
from django.urls import path

from franchise import views


app_name = "franchise"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('account/', views.account, name="account"),

    path('items/', views.items, name="items"),
    path('variants/', views.variants, name="variants"),

    path('flash-sales/', views.flashsale, name="flashsale"),
    path('flash-sales/delete/<int:id>/', views.flashsale_delete, name="flashsale_delete"),
    path('flash-sales/add/<int:id>/', views.flashsale_add, name="flashsale_add"),

    path('todays-deals/', views.todaysdeal, name="todaysdeal"),
    path('todays-deals/delete/<int:id>/', views.todaysdeal_delete, name="todaysdeal_delete"),
    path('todays-deals/add/<int:id>/', views.todaysdeal_add, name="todaysdeal_add"),

    path('banners/', views.banners, name="banners"),
    path('banners/delete/<int:id>/', views.banners_delete, name="banners_delete"),
    path('banners/add/<str:type>/', views.banners_add, name="banners_add"),

    path('posters/', views.posters, name="posters"),
    path('posters/delete/<int:id>/', views.posters_delete, name="posters_delete"),
    path('posters/add/<str:type>/', views.posters_add, name="posters_add"),

    path('static/', views.static, name="static"),
    path('static/delete/<int:id>/', views.static_delete, name="static_delete"),
    path('static/add/<str:type>/', views.static_add, name="static_add"),

]

managers/urls.py
from django.urls import path

from managers import views


app_name = "managers"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('account/', views.account, name="account"),

    path('categories/', views.categories, name="categories"),
    path('categories/add/', views.categories_add, name="categories_add"),
    path('categories/edit/<int:id>/', views.categories_edit, name="categories_edit"),
    path('categories/delete/<int:id>/', views.categories_delete, name="categories_delete"),

    path('products/', views.products, name="products"),
    path('products/add/', views.products_add, name="products_add"),
    path('products/edit/<int:id>/', views.products_edit, name="products_edit"),
    path('products/delete/<int:id>/', views.products_delete, name="products_delete"),

    path('franchise/', views.franchise, name="franchise"),
    path('franchise/add/', views.franchise_add, name="franchise_add"),
    path('franchise/edit/<int:id>/', views.franchise_edit, name="franchise_edit"),
    path('franchise/delete/<int:id>/', views.franchise_delete, name="franchise_delete"),

    path('franchise/items/<int:id>/', views.franchise_items, name="franchise_items"),
    path('franchise/items/add/<int:id>/', views.franchise_items_add, name="franchise_items_add"),
    path('franchise/items/edit/<int:id>/', views.franchise_items_edit, name="franchise_items_edit"),
    path('franchise/items/delete/<int:id>/', views.franchise_items_delete, name="franchise_items_delete"),

    path('variations/<int:id>/', views.variations, name="variations"),
    path('variations/add/<int:id>/', views.variations_add, name="variations_add"),
    path('variations/edit/<int:id>/', views.variations_edit, name="variations_edit"),
    path('variations/delete/<int:id>/', views.variations_delete, name="variations_delete"),

    path('stocks/<int:id>/', views.stocks, name="stocks"),
    path('stocks/edit/<int:id>/', views.stocks_edit, name="stocks_edit"),

    path('time-slots/', views.timeslots, name="timeslots"),
    path('time-slots/add/', views.timeslots_add, name="timeslots_add"),
    path('time-slots/edit/<int:id>/', views.timeslots_edit, name="timeslots_edit"),
    path('time-slots/delete/<int:id>/', views.timeslots_delete, name="timeslots_delete"),

    path('customers/', views.customers, name="customers"),

    path('franchise/users/', views.franchise_users, name="franchise_users"),
    path('franchise/users/add/', views.franchise_users_add, name="franchise_users_add"),
    path('franchise/users/edit/<int:id>/', views.franchise_users_edit, name="franchise_users_edit"),
    path('franchise/users/delete/<int:id>/', views.franchise_users_delete, name="franchise_users_delete"),

    path('delivery-boys/', views.deliveryboys, name="deliveryboys"),
    path('delivery-boys/add/<int:id>/', views.deliveryboys_add, name="deliveryboys_add"),
    # path('delivery-boys/add/in/<int:id>/', views.deliveryboys_add_in, name="deliveryboys_add_in"),
    # path('delivery-boys/edit/<int:id>/', views.deliveryboys_edit, name="deliveryboys_edit"),
    # path('delivery-boys/delete/<int:id>/', views.deliveryboys_delete, name="deliveryboys_delete"),

    path('notifications/', views.notifications, name="notifications"),
    path('notifications/send/<int:id>/', views.notifications_send, name="notifications_send"),
    # path('notifications/send/all/', views.notifications_send_all, name="notifications_send_all"),

    # path('banners/', views.banners, name="banners"),
    # path('banners/add/', views.banners_add, name="banners_add"),
    # path('banners/edit/<int:id>/', views.banners_edit, name="banners_edit"),
    # path('banners/delete/<int:id>/', views.banners_delete, name="banners_delete"),

    # path('posters/', views.posters, name="posters"),
    # path('posters/add/', views.posters_add, name="posters_add"),
    # path('posters/edit/<int:id>/', views.posters_edit, name="posters_edit"),
    # path('posters/delete/<int:id>/', views.posters_delete, name="posters_delete"),

    # path('static-banners/', views.static, name="static"),
    # path('static-banners/add/', views.static_add, name="static_add"),
    # path('static-banners/edit/<int:id>/', views.static_edit, name="static_edit"),
    # path('static-banners/delete/<int:id>/', views.static_delete, name="static_delete"),

    # path('todays-deals/', views.todaysdeals, name="todaysdeals"),
    # path('todays-deals/add/', views.todaysdeals_add, name="todaysdeals_add"),
    # path('todays-deals/edit/<int:id>/', views.todaysdeals_edit, name="todaysdeals_edit"),
    # path('todays-deals/delete/<int:id>/', views.todaysdeals_delete, name="todaysdeals_delete"),

    # path('flash-sales/', views.flashsales, name="flashsales"),
    # path('flash-sales/add/', views.flashsales_add, name="flashsales_add"),
    # path('flash-sales/edit/<int:id>/', views.flashsales_edit, name="flashsales_edit"),
    # path('flash-sales/delete/<int:id>/', views.flashsales_delete, name="flashsales_delete"),

    # path('offers/', views.offers, name="offers"),
    # path('offers/add/', views.offers_add, name="offers_add"),
    # path('offers/edit/<int:id>/', views.offers_edit, name="offers_edit"),
    # path('offers/delete/<int:id>/', views.offers_delete, name="offers_delete"),
]

web/urls.py
from django.urls import path

from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path("privacy/", views.privacy, name="privacy" ),
    path("contact/", views.contact, name="contact" ),
    path("about/", views.about, name="about" ),
    path("return/", views.return_refund, name="return_refund" ),
    path("terms/", views.terms, name="terms" )
]

notifications/models.py
from django.db import models

from users.models import User


class Notification(models.Model):
    created_datetime = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=500)
    body = models.TextField()
    sent_to = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        db_table = 'notifications_notification'
        verbose_name = 'notification'
        verbose_name_plural = 'notifications'
        ordering = ('-id',)

    def __str__(self):

        return self.title

managers/forms.py
from django import forms

from products.models import Category, Item, VariantDetail, FranchiseItem
from franchise.models import Franchise, TimeSlot
from promotions.models import FlashSale, TodayDeal, Banner, StaticBanner, Poster, Offer
from users.models import User



class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","phone_number","email","password"]

        widgets = {
            "first_name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Full Name"}),
            "phone_number":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Mobile Number"}),
            "email":forms.widgets.EmailInput(attrs={"class": "form-control","placeholder":"Email Address"}),
            "password":forms.widgets.PasswordInput(attrs={"class": "form-control","placeholder":"Password"}),
        }


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ["name","image"]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Category Title"}),
            "image":forms.widgets.FileInput(attrs={"class": "form-control"}),
        }


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["name","image","category","description"]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Product Title"}),
            "image":forms.widgets.FileInput(attrs={"class": "form-control"}),
            "category":forms.widgets.Select(attrs={"class": "form-control"}),
            "description":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Product Description"}),
        }



class FranchiseForm(forms.ModelForm):
    class Meta:
        model = Franchise
        fields = ["name","address","latitude","longitude","base_charge","base_distance","extra_charge","extra_distance","free_delivery_cart","delivery_distance"]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Franchise Name"}),
            "address":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Franchise Address"}),
            "latitude":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Location Latitude"}),
            "longitude":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Location Longitude"}),
            "base_charge":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Base Delivery Charge for Base Distance"}),
            "base_distance":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Base Delivery Distance in KM"}),
            "extra_distance":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Extra Distance in KM"}),
            "extra_charge":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Extra Delivery Charge per Extra Distance"}),
            "free_delivery_cart":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Free Delivery Available Cart Value"}),
            "delivery_distance":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Deliverable Distance in KM"}),
        }
    


class VariantDetailForm(forms.ModelForm):
    class Meta:
        model = VariantDetail
        fields = ["name","image","per_unit_price",]

        widgets = {
            "name":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Vraiant Name"}),
            "image":forms.widgets.FileInput(attrs={"class": "form-control"}),
            "per_unit_price":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Unit Price"}),
        }


class FranchiseItemForm(forms.ModelForm):
    class Meta:
        model = FranchiseItem
        fields = ["item","unit","unit_quantity","per_unit_price","net_weight","gross_weight","delivery_distance"]

        widgets = {
            "item":forms.widgets.Select(attrs={"class": "form-control"}),
            "unit":forms.widgets.Select(attrs={"class": "form-control"}),
            "unit_quantity":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Unit Quantity"}),
            "per_unit_price":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Unit Price"}),
            "net_weight":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Net Weight"}),
            "gross_weight":forms.widgets.TextInput(attrs={"class": "form-control","placeholder":"Gross Weight"}),
            "delivery_distance":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Delivery Distance"}),
        }


class FranchiseItemStockForm(forms.ModelForm):
    class Meta:
        model = FranchiseItem
        fields = ["in_stock"]

        widgets = {
            "in_stock":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Stock"}),
        }


class TimeSlotForm(forms.ModelForm):
    class Meta:
        model = TimeSlot
        fields = ["franchise","from_time","to_time",]

        widgets = {
            "franchise":forms.widgets.Select(attrs={"class": "form-control"}),
            "from_time":TimeInput(attrs={"class": "form-control"}),
            "to_time":TimeInput(attrs={"class": "form-control"}),
        }



class FlashSaleForm(forms.ModelForm):
    class Meta:
        model = FlashSale
        fields = ["franchise_item","special_price"]

        widgets = {
            "franchise_item":forms.widgets.Select(attrs={"class": "form-control"}),
            "special_price":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Special Price"}),
        }


class TodayDealForm(forms.ModelForm):
    class Meta:
        model = TodayDeal
        fields = ["franchise_item","special_price"]

        widgets = {
            "franchise_item":forms.widgets.Select(attrs={"class": "form-control"}),
            "special_price":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Special Price"}),
        }



class TodayDealForm(forms.ModelForm):
    class Meta:
        model = TodayDeal
        fields = ["franchise_item","special_price"]

        widgets = {
            "franchise_item":forms.widgets.Select(attrs={"class": "form-control"}),
            "special_price":forms.widgets.NumberInput(attrs={"class": "form-control","placeholder":"Special Price"}),
        }

api/v1/franchise/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework_simplejwt.tokens import RefreshToken
from django.contrib.auth import authenticate




@api_view(["POST"])
@permission_classes ([AllowAny])
def login(request):

    username=request.POST.get('username')
    password=request.POST.get('password')

    if username and password:
        user = authenticate(request, username=username, password=password)

        if user.is_franchise:
            refresh = RefreshToken.for_user(user)


            response_data = {
                "status_code" : 6000,
                "data": {
                    "id": user.id,
                    "username" : user.username,
                    "name" : user.first_name,
                    "email" : user.email,
                    "pnone_number": user.phone_number,
                    'refresh': str(refresh),
                    'access': str(refresh.access_token),
                    "message": "Successfully logged in"
                },

            }
        
        else:
            response_data = {
                "status_code" : 6001,
                "data": {
                    "message": "Invalid login credentials or not allowed"
                },
            }
    else:
        response_data = {
            "status_code" : 6001,
            "data": {
                "message": "Invalid login credentials or not allowed"
            },
        }

    return Response(response_data)

customers/views.py
from django.shortcuts import render

# Create your views here.

notifications/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render

# Create your views here.

templates/manager/categories.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/admin-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0;">
                                    <h4 class="card-title">{{name}}</h4>
                                    <a href="{% url 'managers:categories_add' %}" class="btn mb-1 btn-primary btn-rounded color-white">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>TITLE</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>
                                                        <div style="width: 70px;">
                                                            <img src="{{instance.image.url}}" alt="" style="width: 100%; display: block;">
                                                        </div>
                                                    </td>
                                                    <td>{{instance.name}}</td>
                                                    <td>
                                                        <a href="{% url 'managers:categories_edit' id=instance.id %}" class="btn mb-1 btn-primary color-white">
                                                            <i class="icon-pencil menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Edit
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'managers:categories_delete' id=instance.id %}" class="btn mb-1 btn-danger color-white">
                                                            <i class="icon-trash menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Delete
                                                        </a>
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}

templates/manager/f-users.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/admin-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0;">
                                    <h4 class="card-title">{{name}}</h4>
                                    <a href="{% url 'managers:franchise_users_add' %}" class="btn mb-1 btn-primary btn-rounded color-white">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>FRANCHISE</th>
                                                <th>NAME</th>
                                                <th>MOBILE</th>
                                                <th>EMAIL</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>{{instance.franchise}}</td>
                                                    <td>{{instance.user.first_name}}</td>
                                                    <td>{{instance.user.phone_number}}</td>
                                                    <td>{{instance.user.email}}</td>
                                                    <td>
                                                        <a href="{% url 'managers:franchise_users_edit' id=instance.id %}" class="btn mb-1 btn-primary color-white">
                                                            <i class="icon-pencil menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Edit
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'managers:franchise_users_delete' id=instance.id %}" class="btn mb-1 btn-danger color-white">
                                                            <i class="icon-trash menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Delete
                                                        </a>
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}

templates/manager/products.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/admin-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0;">
                                    <h4 class="card-title">{{name}}</h4>
                                    <a href="{% url 'managers:products_add' %}" class="btn mb-1 btn-primary btn-rounded color-white">ADD NEW</a>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>TITLE</th>
                                                <th>CATEGORY</th>
                                                <th>EDIT</th>
                                                <th>DELETE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>
                                                        <div style="width: 70px;">
                                                            <img src="{{instance.image.url}}" alt="" style="width: 100%; display: block;">
                                                        </div>
                                                    </td>
                                                    <td>{{instance.name}}</td>
                                                    <td>{{instance.category}}</td>
                                                    <td>
                                                        <a href="{% url 'managers:products_edit' id=instance.id %}" class="btn mb-1 btn-primary color-white">
                                                            <i class="icon-pencil menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Edit
                                                        </a>
                                                    </td>
                                                    <td>
                                                        <a href="{% url 'managers:products_delete' id=instance.id %}" class="btn mb-1 btn-danger color-white">
                                                            <i class="icon-trash menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Delete
                                                        </a>
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}