web/urls.py
from django.urls import path

from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path("privacy/", views.privacy, name="privacy" ),
    path("contact/", views.contact, name="contact" ),
    path("about/", views.about, name="about" ),
    path("return/", views.return_refund, name="return_refund" ),
    path("terms/", views.terms, name="terms" )
]

templates/web/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C-FRESH | About us</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}"  type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="{% static 'web/images/favicon.png' %}"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static 'web/images/mockup.png' %}" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>

    <section id="title">
        <section class="wrapper">
            <h1>About Us</h1>
        </section>
    </section>

    <section id="content">
        <section class="wrapper">
            {% for about in abouts %}
                <p>{{about.description|safe}}</p>
            {% endfor %}
        </section>
    </section>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
</body>
</html>

templates/web/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C-FRESH | Contact Us</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}"  type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="web/images/favicon.png"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="./web/images/mockup.png" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>
    <section id="title">
        <section class="wrapper">
            <h1>CONTACT US</h1>
        </section>
    </section>

    <section id="contact">
        <section class="wrapper">
            <div class="left">
                <form action="" method="post">
                    <div class="field">
                        <input type="text" name="name" placeholder="Enter your name">
                    </div>
                    <div class="field">
                        <input type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="field">
                        <input type="number" name="phone" placeholder="Mobile number">
                    </div>
                    <div class="field">
                        <textarea type="textarea" name="email" placeholder="Enter your message"></textarea>
                    </div>
                    <div class="button">
                        <button type="submit" class="submit">SUBMIT</button>
                    </div>
                </form>
            </div>
            <div class="right">
                <span>CONTACT</span>
                <h3>Contact with us for any kind of information</h3>
                <p>We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. 
                    Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app in Kozhikode City.
                </p> <br/>
                <p>NO.2/748 PALAZHI <br/> PAALA ROAD PANTHEERANKAVE <br/> KOZHIKODE KERALA 673014</p>
                <br/>
                <p>Mob: +91 9445 992 992</p>
                <p>Email: support@cfresh.in</p>
            </div>
        </section>
    </section>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
</body>
</html>

templates/web/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}" type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="{% static 'web/images/favicon.png' %}"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static 'web/images/mockup.png' %}" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>

    <header>
        <section class="wrapper">
            <div class="top">
                <h1>
                    <a href="{% url 'web:index' %}">
                        <img src="./{% static 'web/images/favicon.png' %}" alt="logo">
                    </a>
                </h1>
            </div>
            <div class="bottom">
                <div class="left">
                    <h1>Introducing a cFRESH culture.</h1>
                    <p>Fresh Fish Anywhere.</p>
                    <div class="buttons">
                        {% if links %}
                            {% for link in links %}
                                <a href="{{link.android}}">
                                    <img src="./{% static 'web/images/appstore.png' %}" alt="playstore">
                                </a>
                                <a href="{{link.ios}}">
                                    <img src="./{% static 'web/images/playstore.png' %}" alt="apple">
                                </a>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                <div class="right">
                    <img src="./{% static 'web/images/mockup.png' %}" alt="mockup">
                </div>
            </div>
        </section>
    </header>

    <section id="contact">
        <section class="wrapper">
            <div class="left">
                <form action="" method="post">
                    <div class="field">
                        <input type="text" name="name" placeholder="Enter your name">
                    </div>
                    <div class="field">
                        <input type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="field">
                        <input type="number" name="phone" placeholder="Mobile number">
                    </div>
                    <div class="field">
                        <textarea type="textarea" name="email" placeholder="Enter your message"></textarea>
                    </div>
                    <div class="button">
                        <button type="submit" class="submit">SUBMIT</button>
                    </div>
                </form>
            </div>
            <div class="right">
                <span>CONTACT</span>
                <h3>Contact with us for any kind of information</h3>
                <p>We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. 
                    Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app in Kozhikode City.
                </p>
            </div>
        </section>
    </section>

    <footer>
        <section class="wrapper">
            <div class="left">
                <img src="./{% static 'web/images/favicon.png' %}" alt="logo">
                <p>All Right Reserved 2020 © C-FRESH.</p>
            </div>
            <div class="middle">
                <h3>Useful Links</h3>
                <ul>
                    <li><a href="{% url 'web:about' %}">About Us</a></li>
                    <li><a href="{% url 'web:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'web:privacy' %}">Privacy Policy</a></li>
                    <li><a href="{% url 'web:terms' %}">Terms & Conditions</a></li>
                    <li><a href="{% url 'web:return_refund' %}">Cancellation/Refund Policy</a></li>
                </ul>
            </div>
            <div class="right">
                <ul>
                    <li>
                        <a href="#"><img src="./{% static 'web/images/socail/facebook.png' %}" alt="social"></a>
                    </li>
                    <li>
                        <a href="#"><img src="./{% static 'web/images/socail/instagram.png' %}" alt="social"></a>
                    </li>
                    <li>
                        <a href="#"><img src="./{% static 'web/images/socail/linkedin.png' %}" alt="social"></a>
                    </li>
                    <li>
                        <a href="#"><img src="./{% static 'web/images/socail/twitter.png' %}" alt="social"></a>
                    </li>
                </ul>
            </div>
        </section>
    </footer>
    
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
    
</body>
</html>

templates/web/privacy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}"  type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="{% static 'web/images/favicon.png' %}"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static 'web/images/mockup.png' %}" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>
    <section id="title">
        <section class="wrapper">
            <h1>Privacy Policy</h1>
        </section>
    </section>

    <section id="content">
        <section class="wrapper">
            {% for policy in privacies %}
                <p>{{policy.description|safe}}</p>
            {% endfor %}
        </section>
    </section>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
</body>
</html>

templates/web/return.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C-FRESH | Return & Refund</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}"  type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="{% static 'web/images/favicon.png' %}"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static './web/images/mockup.png' %}" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>
    <section id="title">
        <section class="wrapper">
            <h1>Return & Refund</h1>
        </section>
    </section>

    <section id="content">
        <section class="wrapper">
            {% for refund in refunds %}
                <p>{{refund.description|safe}}</p>
            {% endfor %}
        </section>
    </section>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
</body>
</html>

templates/web/terms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>C-FRESH | Terms of use</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}"  type="text/css" />

    <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="{% static 'web/images/favicon.png' %}"
    />

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta property="og:image" content="{% static 'web/images/mockup.png' %}" />
    <meta name="description" content="We present to you the Moosakkai's CFRESH mobile app, Delivers chemical free fishes with a wide range of exquisite options. Experience the delicate fishes of Kerala at a reasonable and affordable price with Cfresh app." />
    <meta name="keywords" content="cfresh, cfresh app, cfresh fish delivery, fish delivery kerala, home fresh deliver, fish home delivery kerala, cfresh calicut, fish calicut" />
</head>
<body>
    <section id="title">
        <section class="wrapper">
            <h1>Terms of Use</h1>
        </section>
    </section>

    <section id="content">
        <section class="wrapper">
            {% for ter in term %}
                <p>{{ter.description|safe}}</p>
            {% endfor %}
        </section>
    </section>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <a href="https://api.whatsapp.com/send?phone=%2B919446992992&text=Hy" class="float" target="_blank">
        <i class="fa fa-whatsapp my-float"></i>
    </a>
</body>
</html>