cfresh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, re_path, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/manager/', include('api.v1.manager.urls')),
    path('api/v1/customer/', include('api.v1.customer.urls')),
    path('', include('web.urls',namespace="web")),
    path('api/v1/franchise/', include('api.v1.franchise.urls')),
    path('manager/', include('managers.urls',namespace="managers")),
    path('franchise/', include('franchise.urls',namespace="franchise")),

]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

franchise/urls.py
from django.urls import path

from franchise import views


app_name = "franchise"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('account/', views.account, name="account"),

    path('items/', views.items, name="items"),
    path('variants/', views.variants, name="variants"),

    path('flash-sales/', views.flashsale, name="flashsale"),
    path('flash-sales/delete/<int:id>/', views.flashsale_delete, name="flashsale_delete"),
    path('flash-sales/add/<int:id>/', views.flashsale_add, name="flashsale_add"),

    path('todays-deals/', views.todaysdeal, name="todaysdeal"),
    path('todays-deals/delete/<int:id>/', views.todaysdeal_delete, name="todaysdeal_delete"),
    path('todays-deals/add/<int:id>/', views.todaysdeal_add, name="todaysdeal_add"),

    path('banners/', views.banners, name="banners"),
    path('banners/delete/<int:id>/', views.banners_delete, name="banners_delete"),
    path('banners/add/<str:type>/', views.banners_add, name="banners_add"),

    path('posters/', views.posters, name="posters"),
    path('posters/delete/<int:id>/', views.posters_delete, name="posters_delete"),
    path('posters/add/<str:type>/', views.posters_add, name="posters_add"),

    path('static/', views.static, name="static"),
    path('static/delete/<int:id>/', views.static_delete, name="static_delete"),
    path('static/add/<str:type>/', views.static_add, name="static_add"),

]

managers/urls.py
from django.urls import path

from managers import views


app_name = "managers"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('account/', views.account, name="account"),

    path('categories/', views.categories, name="categories"),
    path('categories/add/', views.categories_add, name="categories_add"),
    path('categories/edit/<int:id>/', views.categories_edit, name="categories_edit"),
    path('categories/delete/<int:id>/', views.categories_delete, name="categories_delete"),

    path('products/', views.products, name="products"),
    path('products/add/', views.products_add, name="products_add"),
    path('products/edit/<int:id>/', views.products_edit, name="products_edit"),
    path('products/delete/<int:id>/', views.products_delete, name="products_delete"),

    path('franchise/', views.franchise, name="franchise"),
    path('franchise/add/', views.franchise_add, name="franchise_add"),
    path('franchise/edit/<int:id>/', views.franchise_edit, name="franchise_edit"),
    path('franchise/delete/<int:id>/', views.franchise_delete, name="franchise_delete"),

    path('franchise/items/<int:id>/', views.franchise_items, name="franchise_items"),
    path('franchise/items/add/<int:id>/', views.franchise_items_add, name="franchise_items_add"),
    path('franchise/items/edit/<int:id>/', views.franchise_items_edit, name="franchise_items_edit"),
    path('franchise/items/delete/<int:id>/', views.franchise_items_delete, name="franchise_items_delete"),

    path('variations/<int:id>/', views.variations, name="variations"),
    path('variations/add/<int:id>/', views.variations_add, name="variations_add"),
    path('variations/edit/<int:id>/', views.variations_edit, name="variations_edit"),
    path('variations/delete/<int:id>/', views.variations_delete, name="variations_delete"),

    path('stocks/<int:id>/', views.stocks, name="stocks"),
    path('stocks/edit/<int:id>/', views.stocks_edit, name="stocks_edit"),

    path('time-slots/', views.timeslots, name="timeslots"),
    path('time-slots/add/', views.timeslots_add, name="timeslots_add"),
    path('time-slots/edit/<int:id>/', views.timeslots_edit, name="timeslots_edit"),
    path('time-slots/delete/<int:id>/', views.timeslots_delete, name="timeslots_delete"),

    path('customers/', views.customers, name="customers"),

    path('franchise/users/', views.franchise_users, name="franchise_users"),
    path('franchise/users/add/', views.franchise_users_add, name="franchise_users_add"),
    path('franchise/users/edit/<int:id>/', views.franchise_users_edit, name="franchise_users_edit"),
    path('franchise/users/delete/<int:id>/', views.franchise_users_delete, name="franchise_users_delete"),

    path('delivery-boys/', views.deliveryboys, name="deliveryboys"),
    path('delivery-boys/add/<int:id>/', views.deliveryboys_add, name="deliveryboys_add"),
    # path('delivery-boys/add/in/<int:id>/', views.deliveryboys_add_in, name="deliveryboys_add_in"),
    # path('delivery-boys/edit/<int:id>/', views.deliveryboys_edit, name="deliveryboys_edit"),
    # path('delivery-boys/delete/<int:id>/', views.deliveryboys_delete, name="deliveryboys_delete"),

    path('notifications/', views.notifications, name="notifications"),
    path('notifications/send/<int:id>/', views.notifications_send, name="notifications_send"),
    # path('notifications/send/all/', views.notifications_send_all, name="notifications_send_all"),

    # path('banners/', views.banners, name="banners"),
    # path('banners/add/', views.banners_add, name="banners_add"),
    # path('banners/edit/<int:id>/', views.banners_edit, name="banners_edit"),
    # path('banners/delete/<int:id>/', views.banners_delete, name="banners_delete"),

    # path('posters/', views.posters, name="posters"),
    # path('posters/add/', views.posters_add, name="posters_add"),
    # path('posters/edit/<int:id>/', views.posters_edit, name="posters_edit"),
    # path('posters/delete/<int:id>/', views.posters_delete, name="posters_delete"),

    # path('static-banners/', views.static, name="static"),
    # path('static-banners/add/', views.static_add, name="static_add"),
    # path('static-banners/edit/<int:id>/', views.static_edit, name="static_edit"),
    # path('static-banners/delete/<int:id>/', views.static_delete, name="static_delete"),

    # path('todays-deals/', views.todaysdeals, name="todaysdeals"),
    # path('todays-deals/add/', views.todaysdeals_add, name="todaysdeals_add"),
    # path('todays-deals/edit/<int:id>/', views.todaysdeals_edit, name="todaysdeals_edit"),
    # path('todays-deals/delete/<int:id>/', views.todaysdeals_delete, name="todaysdeals_delete"),

    # path('flash-sales/', views.flashsales, name="flashsales"),
    # path('flash-sales/add/', views.flashsales_add, name="flashsales_add"),
    # path('flash-sales/edit/<int:id>/', views.flashsales_edit, name="flashsales_edit"),
    # path('flash-sales/delete/<int:id>/', views.flashsales_delete, name="flashsales_delete"),

    # path('offers/', views.offers, name="offers"),
    # path('offers/add/', views.offers_add, name="offers_add"),
    # path('offers/edit/<int:id>/', views.offers_edit, name="offers_edit"),
    # path('offers/delete/<int:id>/', views.offers_delete, name="offers_delete"),
]

web/urls.py
from django.urls import path

from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path("privacy/", views.privacy, name="privacy" ),
    path("contact/", views.contact, name="contact" ),
    path("about/", views.about, name="about" ),
    path("return/", views.return_refund, name="return_refund" ),
    path("terms/", views.terms, name="terms" )
]

templates/includes/admin-nav.html
    
    {% load static %}

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'managers:index' %}">
                    <h2 class="text-white">CFRESH</h2>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{% static 'web/images/logo.png' %}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'managers:account' %}"><i class="icon-user"></i> <span>Profile</span></a>
                                        </li>
                                        
                                        <hr class="my-2">
                                        <li><a href="{% url 'managers:logout' %}"><i class="icon-key"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="{% url 'managers:index' %}" aria-expanded="false">
                            <i class="icon-home menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Products</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'managers:categories' %}">Categories</a></li>
                            <li><a href="{% url 'managers:products' %}">Products</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="icon-speedometer menu-icon"></i><span class="nav-text">Orders</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-cloud-upload menu-icon"></i><span class="nav-text">Franchise</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'managers:franchise' %}">Franchise</a></li>
                            <li><a href="{% url 'managers:timeslots' %}">Time Slots</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-user menu-icon"></i><span class="nav-text">Users</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'managers:customers' %}">Customers</a></li>
                            <li><a href="{% url 'managers:franchise_users' %}">Franchise</a></li>
                            <li><a href="{% url 'managers:deliveryboys' %}">Delivery Boys</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-heart menu-icon"></i><span class="nav-text">Promotions</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="#">Banners</a></li>
                            <li><a href="#">Posters</a></li>
                            <li><a href="#">Static Banners</a></li>
                            <li><a href="{% url 'managers:notifications' %}">Notifications</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-tag menu-icon menu-icon"></i><span class="nav-text">Special Sales</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="#">Today's Deals</a></li>
                            <li><a href="#">Flash Sales</a></li>
                            <li><a href="#">Offers</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-star menu-icon"></i><span class="nav-text">Pages</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="#">About</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Terms of use</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-wrench menu-icon"></i><span class="nav-text">Settings</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'managers:account' %}">Profile</a></li>
                            <li><a href="{% url 'managers:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->

templates/includes/franchise-nav.html
    
    {% load static %}

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="{% url 'franchise:index' %}">
                    <h2 class="text-white">CFRESH</h2>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{% static 'web/images/logo.png' %}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile animated fadeIn dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href="{% url 'franchise:account' %}"><i class="icon-user"></i> <span>Profile</span></a>
                                        </li>
                                        
                                        <hr class="my-2">
                                        <li><a href="{% url 'franchise:logout' %}"><i class="icon-key"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll">
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="{% url 'franchise:index' %}" aria-expanded="false">
                            <i class="icon-home menu-icon"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-globe-alt menu-icon"></i><span class="nav-text">Items</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'franchise:items' %}">Items</a></li>
                            <li><a href="{% url 'franchise:variants' %}">Variants</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="#" aria-expanded="false">
                            <i class="icon-speedometer menu-icon"></i><span class="nav-text">Orders</span>
                        </a>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-heart menu-icon"></i><span class="nav-text">Promotions</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'franchise:banners' %}">Banners</a></li>
                            <li><a href="{% url 'franchise:posters' %}">Posters</a></li>
                            <li><a href="{% url 'franchise:static' %}">Static Banners</a></li>
                            <li><a href="#">Notifications</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-tag menu-icon menu-icon"></i><span class="nav-text">Special Sales</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'franchise:todaysdeal' %}">Today's Deals</a></li>
                            <li><a href="{% url 'franchise:flashsale' %}">Flash Sales</a></li>
                        </ul>
                    </li>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="icon-wrench menu-icon"></i><span class="nav-text">Settings</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'franchise:account' %}">Profile</a></li>
                            <li><a href="{% url 'franchise:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->