api/v1/franchise/urls.py
from django.urls import path

from api.v1.franchise import views


urlpatterns = [
    path('login/', views.login),

]

franchise/urls.py
from django.urls import path

from franchise import views


app_name = "franchise"

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('account/', views.account, name="account"),

    path('items/', views.items, name="items"),
    path('variants/', views.variants, name="variants"),

    path('flash-sales/', views.flashsale, name="flashsale"),
    path('flash-sales/delete/<int:id>/', views.flashsale_delete, name="flashsale_delete"),
    path('flash-sales/add/<int:id>/', views.flashsale_add, name="flashsale_add"),

    path('todays-deals/', views.todaysdeal, name="todaysdeal"),
    path('todays-deals/delete/<int:id>/', views.todaysdeal_delete, name="todaysdeal_delete"),
    path('todays-deals/add/<int:id>/', views.todaysdeal_add, name="todaysdeal_add"),

    path('banners/', views.banners, name="banners"),
    path('banners/delete/<int:id>/', views.banners_delete, name="banners_delete"),
    path('banners/add/<str:type>/', views.banners_add, name="banners_add"),

    path('posters/', views.posters, name="posters"),
    path('posters/delete/<int:id>/', views.posters_delete, name="posters_delete"),
    path('posters/add/<str:type>/', views.posters_add, name="posters_add"),

    path('static/', views.static, name="static"),
    path('static/delete/<int:id>/', views.static_delete, name="static_delete"),
    path('static/add/<str:type>/', views.static_add, name="static_add"),

]

web/urls.py
from django.urls import path

from web import views


app_name = "web"

urlpatterns = [
    path('', views.index, name="index"),
    path("privacy/", views.privacy, name="privacy" ),
    path("contact/", views.contact, name="contact" ),
    path("about/", views.about, name="about" ),
    path("return/", views.return_refund, name="return_refund" ),
    path("terms/", views.terms, name="terms" )
]

franchise/models.py
from django.db import models
from django.db.models import JSONField

from users.models import User
    

class Franchise(models.Model):
    created_datetime = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=256)
    district = models.CharField(max_length=256, default="Malappuram")
    address = models.TextField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    base_charge=models.IntegerField()
    base_distance=models.IntegerField()
    extra_charge=models.IntegerField()
    extra_distance=models.IntegerField()
    free_delivery_cart=models.FloatField(default=0)
    instant_delivery=models.BooleanField(default=True)
    delivery_distance=models.FloatField()

    class Meta:
        db_table = 'franchise_franchise'
        verbose_name = 'franchise'
        verbose_name_plural = 'franchises'
        ordering = ('-id',)

    def __str__(self):

        return self.name
    


class FranchiseUser(models.Model):
    created_datetime = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE)

    class Meta:
        db_table = 'franchise_franchise_user'
        verbose_name = 'franchise user'
        verbose_name_plural = 'franchise users'
        ordering = ('-id',)

    def __str__(self):

        return self.user.first_name
    


class TimeSlot(models.Model):
    created_datetime = models.DateTimeField(auto_now=True)
    from_time = models.TimeField()
    to_time = models.TimeField()
    franchise = models.ForeignKey(Franchise, on_delete=models.CASCADE)

    class Meta:
        db_table = 'franchise_time_slot'
        verbose_name = 'time slot'
        verbose_name_plural = 'time slots'
        ordering = ('-id',)

    def __str__(self):

        return f'{self.franchise}-{self.from_time.strftime("%H:%M %p")}-{self.to_time.strftime("%H:%M %p")}'

api/v1/franchise/views.py
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework_simplejwt.tokens import RefreshToken
from django.contrib.auth import authenticate




@api_view(["POST"])
@permission_classes ([AllowAny])
def login(request):

    username=request.POST.get('username')
    password=request.POST.get('password')

    if username and password:
        user = authenticate(request, username=username, password=password)

        if user.is_franchise:
            refresh = RefreshToken.for_user(user)


            response_data = {
                "status_code" : 6000,
                "data": {
                    "id": user.id,
                    "username" : user.username,
                    "name" : user.first_name,
                    "email" : user.email,
                    "pnone_number": user.phone_number,
                    'refresh': str(refresh),
                    'access': str(refresh.access_token),
                    "message": "Successfully logged in"
                },

            }
        
        else:
            response_data = {
                "status_code" : 6001,
                "data": {
                    "message": "Invalid login credentials or not allowed"
                },
            }
    else:
        response_data = {
            "status_code" : 6001,
            "data": {
                "message": "Invalid login credentials or not allowed"
            },
        }

    return Response(response_data)

franchise/views.py
import datetime
import csv
import random
from io import TextIOWrapper

from django.shortcuts import get_object_or_404, render, reverse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect

from main.decorators import allow_franchise
from main.functions import generate_form_errors

from managers.models import Manager
from products.models import Category, Item, VariantDetail, FranchiseItem
from franchise.models import FranchiseUser, Franchise, TimeSlot
from customers.models import Customer, CustomerAddress, Cart
from delivery.models import DeliveryAgent
from notifications.models import Notification
from promotions.models import FlashSale, TodayDeal, Banner, StaticBanner, Poster, Offer
from users.models import User


@login_required(login_url="/franchise/login")
@allow_franchise
def index(request):
    
    context= {
        "title": "C-FRESH | Dashboard",
    }
    return render(request, "franchise/index.html", context=context)



def login(request):
    if request.method == 'POST':
        phone_number = request.POST.get('phone_number')
        password = request.POST.get('password')

        if phone_number and password:
            user = authenticate(request, phone_number=phone_number, password=password)
            if user is not None and user.is_franchise:
                auth_login(request, user)

                return HttpResponseRedirect(reverse("franchise:index"))
            else:
                context= {
                    "title": "franchise Login | Home",
                    "error": True,
                    "message": "Invalid credentials or not allowed user"
                }
                return render(request, "franchise/login.html", context=context)
        else:
            context= {
                "title": "franchise Login | Home",
                "error": True,
                "message": "Invalid credentials or not allowed user"
            }
            return render(request, "franchise/login.html", context=context)
    else:
        context= {
            "title" : "franchise Login | Home"
        }
        return render(request, "franchise/login.html", context=context)
    


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("franchise:login"))



@login_required(login_url="/franchise/login")
@allow_franchise
def account(request):
    user=request.user
    franchise= FranchiseUser.objects.get(user=user)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
    }
    return render(request, "franchise/account.html", context=context)


@login_required(login_url="/franchise/login")
@allow_franchise
def items(request):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    instances = FranchiseItem.objects.filter(franchise=franchise)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
        "instances":instances,
    }
    return render(request, "franchise/items.html", context=context)


@login_required(login_url="/franchise/login")
@allow_franchise
def variants(request):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    instances = VariantDetail.objects.filter(franchise=franchise)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
        "instances":instances,
    }
    return render(request, "franchise/variants.html", context=context)


@login_required(login_url="/franchise/login")
@allow_franchise
def flashsale(request):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    instances = FlashSale.objects.filter(franchise=franchise)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
        "instances":instances,
    }
    return render(request, "franchise/flashsale.html", context=context)


@login_required(login_url="/franchise/login")
@allow_franchise
def flashsale_delete(request, id):
    instance = FlashSale.objects.get(id=id)
    item= instance.franchise_item
    item.flash_sale = False
    item.save()
    instance.delete()
    return HttpResponseRedirect(reverse("franchise:flashsale"))


@login_required(login_url="/franchise/login")
@allow_franchise
def flashsale_add(request, id):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    item = FranchiseItem.objects.get(id=id)

    if request.method == "POST":
        price = request.POST.get("price")

        flash_sale = FlashSale.objects.create(
            franchise=franchise,
            franchise_item=item,
            special_price=price,
        )
        item.flash_sale = True
        item.save()
        flash_sale.save()
        return HttpResponseRedirect(reverse("franchise:items"))
    
    else:
        context= {
            "title": "C-FRESH | Dashboard",
            "sub_title": "Profile",
            "name": "My Account",
            "franchise":franchise,
            "item": item,

        }
        return render(request, "franchise/flashsale-add.html", context=context)




@login_required(login_url="/franchise/login")
@allow_franchise
def todaysdeal(request):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    instances = TodayDeal.objects.filter(franchise=franchise)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
        "instances":instances,
    }
    return render(request, "franchise/todaysdeal.html", context=context)



@login_required(login_url="/franchise/login")
@allow_franchise
def todaysdeal_delete(request, id):
    instance = TodayDeal.objects.get(id=id)
    item = instance.franchise_item
    item.todays_deal = False
    item.save()
    instance.delete()
    return HttpResponseRedirect(reverse("franchise:todaysdeal"))



@login_required(login_url="/franchise/login")
@allow_franchise
def todaysdeal_add(request, id):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    item = FranchiseItem.objects.get(id=id)

    if request.method == "POST":
        price = request.POST.get("price")

        todays_deal = TodayDeal.objects.create(
            franchise=franchise,
            franchise_item=item,
            special_price=price,
        )
        item.todays_deal = True
        item.save()
        todays_deal.save()
        return HttpResponseRedirect(reverse("franchise:items"))
    
    else:
        context= {
            "title": "C-FRESH | Dashboard",
            "sub_title": "Profile",
            "name": "My Account",
            "franchise":franchise,
            "item": item,
        }
        return render(request, "franchise/flashsale-add.html", context=context)



@login_required(login_url="/franchise/login")
@allow_franchise
def banners(request):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    instances = Banner.objects.filter(franchise=franchise)
    
    context= {
        "title": "C-FRESH | Dashboard",
        "sub_title": "Profile",
        "name": "My Account",
        "franchise":franchise,
        "instances":instances,
    }
    return render(request, "franchise/banners.html", context=context)



@login_required(login_url="/franchise/login")
@allow_franchise
def banners_delete(request, id):
    instance = Banner.objects.get(id=id)
    instance.delete()
    return HttpResponseRedirect(reverse("franchise:banners"))



@login_required(login_url="/franchise/login")
@allow_franchise
def banners_add(request, type):
    user=request.user
    franchise_user= FranchiseUser.objects.get(user=user)

    franchise = franchise_user.franchise

    if type == "PR":
        instances = FranchiseItem.objects.filter(franchise=franchise)
        product = True
        category = False
    elif type == "CA":
        instances = Category.objects.all()
        product = False
        category = True


    if request.method == "POST":
        model_id = request.POST.get("item")
        name = request.POST.get("name")
        banner = request.FILES.get("image")
        if type == "PR":
            banner = Banner.objects.create(
                franchise = franchise,
                name = name,
                model_id = model_id,
                banner_image =banner,
                banner_type= "PR",
            )
            return HttpResponseRedirect(reverse("franchise:banners"))
        elif type == "CA":
            banner = Banner.objects.create(
                franchise = franchise,
                name = name,
                model_id = model_id,
                banner_image =banner,
                banner_type= "CA",
            )
            return HttpResponseRedirect(reverse("franchise:banners"))
    else:
        context= {
            "title": "C-FRESH | Dashboard",
            "sub_title": "Profile",
            "name": "My Account",
            "franchise":franchise,
            "instances":instances,
            "product":product,
            "category":category,
        }
        return render(request, "franchise/banner-add.html", context=context)



@login_required(login_url="/franchise/login")
@allow_franchise
def posters(request):
    user=request.user

templates/franchise/banners.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/franchise-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0; align-items: center;">
                                    <h4 class="card-title">{{name}}</h4>
                                    <div style="display: flex;justify-content: flex-end; align-items: center;">
                                        <a href="{% url 'franchise:banners_add' type='PR' %}" class="btn mb-1 btn-primary btn-rounded color-white mr-2">ADD FOR PRODUCT</a>
                                        <a href="{% url 'franchise:banners_add' type='CA' %}" class="btn mb-1 btn-primary btn-rounded color-white">ADD FOR CATEGORY</a>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>TITLE</th>
                                                <th>BANNER TYPE</th>
                                                <th>REMOVE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>
                                                        <div style="width: 70px;">
                                                            <img src="{{instance.banner_image.url}}" alt="" style="width: 100%; display: block;">
                                                        </div>
                                                    </td>
                                                    <td>{{instance.name}}</td>
                                                    <td>{{instance.get_banner_type_display}}</td>
                                                    <td>
                                                        <a href="{% url 'franchise:banners_delete' id=instance.id %}" class="btn mb-1 btn-danger color-white">
                                                            <i class="icon-trash menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Delete
                                                        </a>
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}

templates/franchise/flashsale-add.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/franchise-nav.html' %}


        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)" >{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{name}}</h4>
                                <div class="basic-form">
                                    <form action="" method="post" class="ajax redirect" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="form-row">
                                            <div class="form-group col-12 col-md-6">
                                                <label>Special Price</label>
                                                <input type="number"  class="form-control" placeholder="Enter Special Price" name="price" value="{{item.per_unit_price}}">
                                            </div>
                                            <div class="form-group col-12 col-md-6"></div>
                                            <button class=" btn login-form__btn submit button" type="submit">Submit</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}

templates/franchise/items.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/franchise-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0;">
                                    <h4 class="card-title">{{name}}</h4>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>TITLE</th>
                                                <th>CATEGORY</th>
                                                <th>STOCK</th>
                                                <th>UNIT PRICE</th>
                                                <th>FLASH SALE</th>
                                                <th>TODAY'S DEAL</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>
                                                        <div style="width: 70px;">
                                                            <img src="{{instance.item.image.url}}" alt="" style="width: 100%; display: block;">
                                                        </div>
                                                    </td>
                                                    <td>{{instance.item.name}}</td>
                                                    <td>{{instance.item.category}}</td>
                                                    <td>{{instance.in_stock}} KG</td>
                                                    <td>₹ {{instance.per_unit_price}}</td>
                                                    <td>
                                                        {% if instance.flash_sale %}
                                                            <a href="#" class="btn mb-1 btn-warning color-white">
                                                                ADDED
                                                            </a>
                                                        {% else %}
                                                            <a href="{% url 'franchise:flashsale_add' id=instance.id %}" class="btn mb-1 btn-primary color-white">
                                                                ADD
                                                            </a>
                                                        {% endif %}
                                                    </td>
                                                    <td>
                                                        {% if instance.todays_deal %}
                                                            <a href="#" class="btn mb-1 btn-warning color-white">
                                                                ADDED
                                                            </a>
                                                        {% else %}
                                                            <a href="{% url 'franchise:todaysdeal_add' id=instance.id %}" class="btn mb-1 btn-primary color-white">
                                                                ADD
                                                            </a>
                                                        {% endif %}
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}

templates/franchise/posters.html
{% extends "base/admin-base.html" %} {% block container %} {% load static %}


{% include 'includes/franchise-nav.html' %}


<!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0 bg-transparent">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">{{sub_title}}</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">{{name}}</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <div style="display: flex;justify-content: space-between; padding: 15px 30px 0;">
                                    <h4 class="card-title">{{name}}</h4>
                                    <div style="display: flex;justify-content: flex-end; align-items: center;">
                                        <a href="{% url 'franchise:posters_add' type='PR' %}" class="btn mb-1 btn-primary btn-rounded color-white mr-2">ADD FOR PRODUCT</a>
                                        <a href="{% url 'franchise:posters_add' type='CA' %}" class="btn mb-1 btn-primary btn-rounded color-white">ADD FOR CATEGORY</a>
                                    </div>
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>IMAGE</th>
                                                <th>TITLE</th>
                                                <th>POSTER TYPE</th>
                                                <th>REMOVE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                                <tr>
                                                    <td>
                                                        <div style="width: 70px;">
                                                            <img src="{{instance.poster_image.url}}" alt="" style="width: 100%; display: block;">
                                                        </div>
                                                    </td>
                                                    <td>{{instance.name}}</td>
                                                    <td>{{instance.get_poster_type_display}}</td>
                                                    <td>
                                                        <a href="{% url 'franchise:posters_delete' id=instance.id %}" class="btn mb-1 btn-danger color-white">
                                                            <i class="icon-trash menu-icon" style="color:white; font-size: 14px; margin-right: 2px;"></i>
                                                            Delete
                                                        </a>
                                                    </td>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->

{% endblock %}